### ISSUE TITLE
scroll tabs stops working 

### ISSUE THREAD

**Issue by owcraftsman** [joshuacant/tst-wheel_and_double#8] opened 2018-01-12 20:22 UTC
as the title says scroll tabs stops working, 
I do not know why and have not found what may be causing it.
At first I thought it may be a conflict with CCleaner which cleans the browser between every session but a simple close and restart doesn't make it stop working.
I have found a work around by openings Add-ons then TST Mouse wheel and double click" 1.1.0 > options setting appear as I had set them however if I check the "Disable scrolling to change tabs"  box then click save then uncheck it and click save again Scrolling tabs becomes functional again.
This happens intermittently but daily could be just restarting the system which I will try after this post and  report back but non the less annoying.
Anything you can do to help?

**Comment by owcraftsman** [comment] 2018-01-12 20:26
No restarting has no effect for the moment scroll is still working but this doesn;t explain why at least once per day I have to reset it with the work around as described above

**Comment by joshuacant** [comment] 2018-01-12 22:20
Duplicate of #6

**Comment by joshuacant** [comment] 2018-01-12 22:20
It's being worked on, but no ETA. Thanks for the report, you should be CC'd on future updates to #6

**Closed by joshuacant** 2018-01-12 22:20 UTC
