### ISSUE TITLE
Shift-scroll for scrolling the tab sidebar doesn't stop on shift release

### ISSUE THREAD

**Issue by maxaxehax** [joshuacant/tst-wheel_and_double#17] opened 2018-12-11 08:51 UTC
First: Many thanks for the effort to restore old functionality I couldn't imagine living without after FF 57!

I've found the following issue which I've been able to reproduce reliably. First off, my options:

![image](https://user-images.githubusercontent.com/18725890/49793174-d8123a00-fd34-11e8-9ad3-fc0620780104.png)

Reproduce like this:

1. Expand enough tabs so that the tab sidebar shows a scrollbar. Given the options, scrolling should (and does) switch tabs instead of scrolling the sidebar.
2. Shift-scroll should (and does) scroll the sidebar.
3. After scrolling the sidebar like this, the sidebar-scrolling behavior stays enabled even after releasing the shift key.

The only fix seems to be to "Save options" in the addon settings, perhaps trigerring some re-registration. I have a burning suspicion this could be related to the problems in issue #6 where an auto-update can be ruled out as the cause (since for users who don't require shift to sidebar-scroll, the behaviour would change as soon as the tree gets large enough and apparently doesn't switch back to tab switching on its own)

**Comment by joshuacant** [comment] 2018-12-11 14:52
Hi mhaaz, I can recreate this on my end. That feature was added by a contributor. I'm going to ping them and see if they would like to check it out. It seems like the detection of when shift is being pressed and released is off. It might be due to some change in Firefox itself, because the feature worked when it was added.

Hi, @AllenAnthes do you have time to check out this bug?

**Comment by AllenAnthes** [comment] 2018-12-11 16:55
I should be able to poke around a bit later today.

**Comment by joshuacant** [comment] 2018-12-14 22:17
Windows 10 x64, build 1809 (Latest)
Firefox Dev Edition, x64, 65.0b4 (Latest)
Tree Style Tab 2.7.1 (Latest)
TST Mouse Wheel and Double Click 1.3 (Latest)

(Note: The following steps assume you have enough tabs and a small enough vertical window for the tab sidebar to scroll.)

Here's the exact behavior I see (which I believe matches what mhaaz reported), upon checking the "Enable shift to scroll" box and hitting save:
1. Place mouse over tab sidebar.
2. Rotate mouse wheel.
3. Scrolling works normally.
4. Hold down shift.
5. Rotate mouse wheel.
6. Tab view scrolls for the very first wheel rotation, then ceases to work.
7. Release shift.
8. Rotate mouse wheel.
9. Tab view scrolls freely.

At this point, it is no longer possible to change tabs with the wheel. If you hold down shift again and scroll, nothing happens. Tabs don't change. View doesn't scroll. However, if you release shift, and then scroll, the view scrolls freely again. The only way to restore normal operation is to uncheck shift to scroll and hit save, at which point everything works normally again.

My guess is that it's something in Firefox being weird, and probably down to the OS level. I wonder if mhaaz and I both use Windows and you use something else? @mhaaz what OS are you running?

**Comment by AllenAnthes** [comment] 2018-12-14 22:57
Still not able to reproduce.  I tried on Standard, Developer, and Nightly.  I'm also on Windows 10.

I hate the pass the buck but could it potentially be another addon interfering?  

I'll leave the options on and see if I notice anything but the shift-scrolling isn't a functionality I generally use.

**Comment by joshuacant** [comment] 2018-12-14 22:59
Yeah, I don't use it either, to be honest. Maybe it is another addon. I'll try to see if I can narrow it down.

**Comment by amandamana** [comment] 2019-12-19 20:41
It looks like there are a couple problems here.

One seems to be a regression in TST or Firefox where the scrolled message sent to tst-wheel_and_double has a deltaY of zero when the shiftKey is held down. This bug might be platform dependent. I'll notify Piror of this issue.

Strangely the deltaY is correctly -1 or 1 when the altKey is held down, so swapping the modifier keys would be a workaround.

The other issue seems to be unintentionally asking TST to change tabs immediately after scrolling the window.

**Comment by joshuacant** [comment] 2019-12-19 23:46
I don't use this feature at all, so I don't really have any opinions. If someone wanted to fix it up and send a PR, I'd merge it.

**Comment by amandamana** [comment] 2019-12-21 17:52
Would holding Alt while scrolling Firefox on Windows conflict with a default function, such as giving focus to a menubar?

**Comment by joshuacant** [comment] 2019-12-21 21:23
It seems that on Windows, Alt+Scrolling = Forward/Back. I think it must be a built-in feature of Firefox. I didn't test with all my addons disabled, but it's unlikely I have something that would have added that.

**Comment by chrstfer** [comment] 2023-01-27 16:00
Alt-scroll is a firefox built-in feature. The alt+scroll action is controlled by the config string `mousewheel.with_alt.action` (with possible values and related settings outlined [here](http://kb.mozillazine.org/About:config_entries#Mousewheel) though that page seems somewhat out of date with the defaults). This is actually kept separate from the `mousewheel.with_meta.action`, too.

**Comment by Cloom3182** [comment] 2023-07-16 13:17
first of all,thanks a lot for this add-on, it may be the reason why many people use FF, 
but may I ask is Shift-scroll still working? I tried many times but it seems the scrollbar is the only way
if anyone can reply I would be so grateful

**Comment by joshuacant** [comment] 2023-07-16 22:13
I just tested it out (it's not a feature I use or added) and it doesn't seem to be working right. It works a little bit and then gets stuck in window-scroll mode and won't go back to tab-scrolling mode until the setting is toggled off and saved. Is this what you experience?

**Comment by Cloom3182** [comment] 2023-07-17 00:37
thank you so much for reply!
for me, it doesn't seem to work at all,
Windows 10 ;FF is 115.0.2 (64 bit) 
TST 3.9.15;TST Mouse Wheel and Double Click 1.5;
if any other information is needed, I would give it as soon as possible,
thanks again for your reply!

**Comment by joshuacant** [comment] 2023-10-16 21:36
Hi all, I have uploaded a beta version to AMO with some changes that could possibly affect (or fix?) this scrolling bug. If you would like to try it out, visit this link: https://addons.mozilla.org/firefox/downloads/file/4181773/tree_style_tab_mouse_wheel-1.5.4.xpi

It's a fully signed extension by Mozilla, so you can install it in normal Firefox, but it's not pushed out via the main channel. So if you encounter any problems you can let me know and then downgrade to the published version 1.5 here: https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab-mouse-wheel/

Feedback would be appreciated.

**Comment by joshuacant** [comment] 2023-10-16 21:54
I've been informed that at least some people are getting an error on that addons.mozilla.org link. I uploaded the test XPI here: https://github.com/joshuacant/tst-wheel_and_double/releases/tag/1.5.4

**Comment by joshuacant** [comment] 2024-02-19 16:31
I haven't run into any issues with this test build since I uploaded it back in October. I'm going to release it and mark this issue as closed as no one replied. If anyone here is still using this addon and notices bugs with the new version I'm about to publish, please open a new issue.

**Closed by joshuacant** 2024-02-19 16:31 UTC
Labels: bug, help wanted
